project:
  output-dir: _output  
format:
  typst:
    keep-typ: true
    template: template.typ
    bibliographystyle: abnt-ipea.csl 
    filters:
      - critic-markup.lua
    format-resources:
      - abnt-ipea.csl
      - glogo.gif
      - cc_by.svg
    template-partials:
      - typst-template.typ
      - typst-show.typ
      - notes.typ
      - biblio.typ
      - definitions.typ

  