---
format:
  jats: 
    template: scielo.template
    output-ext: "scielo.xml"
    citeproc: true
    filters: 
      - at: post-render
        path: footnote-type.lua

lang: pt

title: "\"Presunção relativa\": quando a narrativa policial é colocada à prova nos processos de tráfico de drogas"


author:
  - id: mj
    # name: #--> default quarto structure does not work with pandoc template 
    #   given: Maria Gorete
    #   family: Marques de Jesus
    #   literal: Maria Gorete Marques de Jesus
    #   dropping-particle: de
    given-names: Maria Gorete
    surname: Marques de Jesus
    email: gorete.marques@gmail.com
    orcid: 0000-0003-2667-8736
    note: >
        Pesquisadora do Núcleo de Estudos da Violência da Universidade de São Paulo (NEV-USP). Professora do departamento de sociologia da Universidade Federal de São Carlos.
    metadata: 
        country-code: BR
    affiliations:
      - id: nevusp
        number: 1
        name: Universidade de São Paulo
        orgname: Universidade de São Paulo
        department: Departamento de Sociologia
        orgdiv: Departamento de Sociologia
        group: Núcleo de Estudos da Violência
        city: São Paulo
        state: SP
        country: Brasil
        url: https://usp.br
      - id: ufscar
        number: 2
        name: Universidade Federal de São Carlos
        orgname: Universidade Federal de São Carlos
        department: Departamento de Sociologia
        orgdiv: Departamento de Sociologia
        city: São Carlos
        state: SP
        country: Brasil
        url: https://ufscar.br
  
  - id: ma
    # name: Mariana Celano de Souza Amaral
    given-names: Mariana Celano de Souza 
    surname: Amaral
    orcid: 0000-0003-1634-8709
    email: mariana.amaral@usp.br
    note: "Mestre pelo programa de pós-graduação em Sociologia pela Universidade de São Paulo (USP)."
    metadata: 
      country-code: BR
    affiliations:
      - id: usp
        name: Universidade de São Paulo
        orgname: Universidade de São Paulo
        department: Departamento de Sociologia
        orgdiv: Departamento de Sociologia
        city: São Paulo
        state: SP
        country: Brasil
        url: www.usp.br
resumo: >
  O presente artigo faz uma análise qualitativa de 36 decisões de
  desclassificação ou absolvição em relação a casos envolvendo condutas
  criminalizadas pela Lei 11.343/2006 (Lei de Drogas) publicadas pelo
  Tribunal de Justiça de São Paulo nos anos de 2010, 2011 e 2017. O
  objetivo é compreender como são tratadas as narrativas policiais nos
  casos em que tais testemunhos não parecem ser centrais para a decisão,
  pois, ao analisar os encaminhamentos dados pelo sistema de justiça
  criminal brasileira, a literatura aponta a hegemonia de condenações
  feitas com base nos testemunhos policiais. Contudo, alguns casos não
  resultam em tal desfecho, sendo a sentença ou a desclassificação da
  conduta para a de porte para uso, ou até absolvição, o que, a princípio,
  contraria a narrativa policial. A investigação reflete, nesse sentido,
  sobre os principais tipos de argumentos  encontrados em tais casos e as
  possibilidades já existentes de eventuais "pontos de fuga" da atuação
  majoritária do judiciário.
palavras-chave: 
  - testemunho policial
  - justiça criminal
  - tráfico de drogas
  - desclassificação
  - absolvição
  
abstract: > 
  This article conducts a qualitative analysis of 36 decisions of
  declassification or acquittal in cases involving behaviors criminalized
  by Law 11.343/2006 (Drug Law) published by the São Paulo State Court of
  Justice in the years 2010, 2011, and 2017. The aim is to comprehend how
  police narratives are handled in cases where such testimonies do not
  appear to be central to the decision. When examining the outcomes within
  the Brazilian criminal justice system, the literature points to the
  predominance of convictions based on police testimonies. However, some
  cases do not result in such outcomes, leading to sentences or
  declassification of the offense to "possession for personal use" or even
  acquittal, which initially contradicts the police narrative. In this
  regard, the investigation reflects on the main types of arguments found
  in such cases and the existing possibilities of potential "escape
  routes" from the predominant judicial approach.
keywords:
  - police testimony
  - criminal justice
  - drug trafficking
  - desclassification
  - acquittal


  
license: "CC BY-NC"


journal:
    publisher-id: se
    id: se
    title: Sociedade & Estado
    abbrev-title: Soc. Estado.
    pissn: 0102-6992
    eissn: 1980-5462
    publisher-name: Departamento de Sociologia da Universidade de Brasília
    publisher-loc: Brasília
    editor: Eduardo Dimitrov

article:
    heading: Artigo Original
    volume: 40
    issue: 1
    year: 2025
    doi: 10.1590/s0102-6992-20243903e50832
    elocation-id: e50832
    received-date:
        year: 2023
        month: 09
        day: 15
    accepted-date:
        year: 2024
        month: 10
        day: 09


bibliography: refs.bib



---

# Introdução 

Ao nos depararmos com algumas informações básicas sobre a população
prisional brasileira, alguns elementos saltam aos olhos. O primeiro
deles, claro, é a quantidade: segundo levantamento disponibilizado pelo
Departamento Penitenciário Nacional (Depen), em junho de 2021 cerca de
678.973 pessoas estavam presas no país[^3]. Destas, cerca de 67% eram
preta ou parda. Já segundo o IBGE, no mesmo período cerca de 52% da
população brasileira se declarou preta ou parda[^4], o que revela desde
logo a seletividade racial presente no sistema de segurança pública e
justiça criminal no Brasil, como alertado por pesquisadores e
organizações de direitos humanos [@barros2008; @santos2012; @sinhoretto2014a; @sinhoretto2014b].

As más condições dos estabelecimentos prisionais brasileiros também são
há muito conhecidas; foram, inclusive, reprovadas publicamente pelo
Supremo Tribunal Federal[^5] e pela Corte Interamericana de Direitos
Humanos[^6]. Também chama a atenção que, entre os principais motivos
para as prisões apresentarem tais contextos, estão as condenações por
crimes previstos na Lei de Drogas (Lei n. 11.343/2006): em junho de
2021, cerca de 205 mil pessoas presas respondiam por tais crimes, o que
representa cerca de 30% do total da população carcerária.

Compreender melhor o que possibilita esse tipo específico de condenação
tem sido o objetivo de diversos estudos recentes[^7]. A partir deles,
foi possível visualizar o papel fundamental que os agentes de segurança
têm no funcionamento dessa engrenagem. Quem afirma ter visto determinado
sujeito vendendo a droga? Define qual é o local de venda de drogas?
Atribui a posse da substância? Figura como testemunha ocular do tráfico?
Declara a "confissão informal" da pessoa acusada? Seleciona aqueles que
vão para o sistema penal e aqueles que não vão? A polícia. A legislação
oferece os critérios, mas quem faz o enquadramento é a polícia. As
expressões utilizadas por esses agentes, baseadas em seu saber
policial[^8], oferecem o repertório que vai traduzir um "fato da
realidade" para um "fato jurídico". O policial torna-se capaz de
identificar um "traficante" e um "usuário", com base em seu
conhecimento, sua experiência, seu "tirocínio", enfim, seu saber.

Será a partir dessa narrativa policial que os operadores do direito vão
extrair as "provas" necessárias para a punição daqueles levados à
justiça por terem sido reconhecidos como "traficantes" pelos policiais
[@jesus2016; @jesus2020]. A recepção das narrativas policiais como verdade é
algo frequente, como demonstra a literatura[^9]. Identificou-se que os
juízes constroem, por meio de mecanismos retóricos, falsas harmonias
entre tais depoimentos e outros elementos tangentes ao processo, que dão
credibilidade para tais narrativas e, ao fim, ensejam uma condenação
[@amaral2018].

Contudo, nem toda pessoa denunciada pela suposta prática de um crime é
presa e condenada por tráfico de drogas. A pesquisa de Mariana Celano de
Souza Amaral (-@amaral2018), por exemplo, identifica em seu *corpus* empírico de
pesquisa casos que resultaram em absolvição e desclassificação do crime
originalmente imputado (tráfico de drogas) para o crime do artigo 28 da
Lei de Drogas (uso), para o qual não há previsão legal de pena de
privação de liberdade[^10]. Em nove casos de um total de 74 sentenças
analisadas, os réus acusados por tráfico de drogas foram absolvidos;
entre estes, em cinco deles apenas a defesa requereu a absolvição, em
três deles tanto a defesa quanto o MP pleitearam por tal medida, e em um
caso não há registro da parte que realizou o pedido. Ademais, entre as
74 sentenças surgiram três desclassificações, ou seja, o magistrado
considerou que o crime cometido foi o de uso, e não de tráfico de drogas
[@amaral2018]. O mesmo pode ser visto na pesquisa de Maria Gorete M. de
Jesus (-@jesus2016), em que foram identificados 24 casos em que houve como
desfecho processual a absolvição ou desclassificação para uso num total
de 667 processos.

Dada a centralidade da narrativa policial nos casos de condenação por
tráfico de drogas, conforme apontado pela literatura especializada, nas
situações em que o desfecho processual é outro, como essas narrativas
são recepcionadas ou tratadas? É essa a pergunta que o presente artigo
busca responder. A princípio, a decisão de absolver ou desclassificar o
crime aparenta estar descolada do relato policial. Nossa hipótese
inicial era a de que nessas decisões a narrativa policial é
explicitamente afastada do centro do caso, o que permitiria a absolvição
ou desclassificação. Contudo, a análise qualitativa das 36 sentenças não
confirmou totalmente tal hipótese. O que parece acontecer, pelo que
pudemos observar dos casos, é uma relativização dessa narrativa
policial. Nos interessa, então, descrever em que medida essa
relativização ocorre, como os juízes argumentam nesses casos e o que
consideram mais relevante para a tomada de decisão.

Antes de apresentar sua exploração, a próxima seção percorre as análises
sobre a recepção das narrativas policiais por juízes encontradas na
literatura e em nossas próprias pesquisas. Em seguida, detalhamos nossa
metodologia de seleção e análise dos casos selecionados. Depois,
apresentamos os resultados e propomos uma discussão que visa a
problematizar o papel central dos magistrados nessas decisões, bem como
a forma como tomam as narrativas policiais nos casos analisados.

# Percorrendo a literatura sobre o tema

A relevância da narrativa policial nas condenações por tráfico de drogas
foi identificada já nas primeiras pesquisas que se detiveram sobre o
processamento desse tipo de crime, após a edição da "nova" Lei de Drogas
no ano de 2006. ~~Luciana Boiteux e Ela Wiecko (2009)~~, por exemplo,
analisaram decisões judiciais publicadas entre 2006 e 2008 nas cidades
de Brasília e Rio de Janeiro. Apesar de não terem esse tema como foco
central de seu estudo, as autoras apontam, já a partir da leitura das
sentenças selecionadas, que "os policiais são os responsáveis pela
montagem das provas a serem apresentadas nos processos, e quase nunca
são questionados em juízo" ~~(Boiteux; Wiecko, 2009, p. 45)~~. Tal
constatação é acompanhada da informação sobre o alto número de
condenações -- no caso da pesquisa de Boiteux e Wiecko, cerca de 76% das
838 sentenças analisadas foram condenatórias ~~(*ibidem*, p. 50)~~.

A importância do depoimento dado pelos policiais nos processos de
tráfico de drogas ficou evidente também em estudo coordenado por @jesus2011, que teve como base 667 casos processados no Estado de São Paulo
entre 2010 e 2011. Nela, constatou-se que em 74% dos casos analisados os
policiais foram as únicas testemunhas nos processos [@jesus2011, p. 55]. Ao mesmo tempo, cerca de 91% dos 449 casos com sentença em
primeira instância tiveram como resultado condenações [@jesus2011, p. 79].
O mesmo padrão foi identificado, mais recentemente, no Rio de Janeiro.
No estudo de Carolina Haber e Natalia Maciel (-@haber2018), que teve como
universo cerca de 3.700 sentenças proferidas entre 2014 e 2016, 94,95%
dos casos contaram com depoimentos de agentes de segurança; além disso,
eles foram os únicos a depor em 62,33% do universo total das
pesquisadoras [@haber2018, p. 9]. Nesse caso, as sentenças
totalmente ou parcialmente condenatórias representaram cerca de 80% do
total [@haber2018, p. 6]. A investigação de Semer, que abrangeu 800
sentenças de oito Estados (São Paulo, Minas Gerais, Bahia, Rio Grande do
Sul, Paraná, Goiás, Maranhão e Pará), corrobora tais conclusões: os
agentes de segurança atuaram como testemunhas em cerca de 90% dos casos
analisados [@semer2019, p. 187]. Na média de todos os estados, as
condenações atingiram o patamar de cerca de 78% dos casos analisados
[@semer2019, p. 237].

Essas constatações também têm ressonância em trabalhos produzidos no
campo do Direito, que buscam avaliar, a partir dos parâmetros legais
estabelecidos pela Constituição Federal, o valor jurídico dos
depoimentos de agentes policiais como testemunhas no processo penal.
~~Luís Carlos Valois (2017)~~, por exemplo, sustenta que a utilização
recorrente desse tipo de testemunho como pilar central das condenações
por tráfico de drogas viola o direito de defesa das pessoas acusadas. É
também a conclusão de Amaral (2018), que identifica que a presunção de
inocência dos réus(rés) não norteia a admissão desse tipo de depoimento
nos processos. Para a autora, a maneira como tal admissão é operada
conforma uma prática processual penal totalmente afastada de princípios
democráticos. Trata-se de prática oposta, portanto, ao sentido de
processo penal defendido por autores como Aury Lopes Jr. [-@lopes2017], Geraldo
Prado [-@prado2005], Jacinto Coutinho [-@coutinho2001] e Rui Cunha Martins [-@martins2013], o qual
sugere, por exemplo, a *democraticidade* como critério e princípio
unificador da boa prática processual [@martins2013, p. 73].

Do ponto de vista sociológico, o fenômeno foi investigado na pesquisa de
[@jesus2016; @jesus2020], que analisa a mobilização dos argumentos dos atores
do sistema de justiça a partir de um repertório de crenças, em que há
quase um ato de "fé" em se acreditar nas narrativas policiais. Juízes
creem que os policiais agem de acordo com a lei, confiam que esses
agentes não utilizaram recursos da violência de forma desnecessária,
sustentam suas decisões no "saber policial" -- por estarem na linha de
frente eles conheceriam e saberiam quem são os verdadeiros traficantes,
na mesma medida em que acreditam que seu papel é defender a sociedade.

Nota-se, portanto, que a importância da palavra policial nos processos
de tráfico de drogas em que há condenação é inequívoca. Tendo isso em
consideração, não se pode deixar de notar que os estudos acima
mencionados também identificam um contingente de processos em que o
resultado é diferente da condenação (desclassificação para porte para
uso ou absolvição) que são, por sua vez, pouco ou nada estudados. É
possível que, nesses casos, haja algum questionamento da narrativa
policial? @semer2019, por exemplo, aponta as controvérsias presentes
nas poucas sentenças em relação a outras cujo desfecho foi a condenação:
juízes/as que questionam a confissão informal, já que é um ato narrado
pelo policial, e não pelo próprio réu em audiência (momento de efetiva
produção de provas processuais); que relativizam os depoimentos
policiais, apontando as contradições entre os testemunhos e detalhes
esquecidos do momento da flagrante e considerados fundamentais para a
configuração do crime de tráfico, como alguma evidência de venda da
droga; que questionam a possibilidade do abuso policial no flagrante;
que defendem que a palavra do policial não pode ser a única prova a
sustentar uma decisão condenatória; que consideram a investigação
frágil; que valorizam os testemunhos de defesa e o consideram relevantes
em detrimento dos depoimentos dos policiais, mesmos estes sendo agentes
públicos no cumprimento do dever legal e, portanto, dignos de
credibilidade. Já @maciel2019 aponta que os dois aspectos que foram
mais considerados nas sentenças absolutórias de seu material -- mesmo
analisado por ela e @haber2018 -- foram as *"condições em que se
desenvolveu a ação"*, presente em cerca de 97% de tais decisões, e o
*"local da ação"*, que apareceu em cerca de 20% dos documentos [@maciel2019, p. 61].

> @jesus2016 também identificou alguns operadores do Direito que
> rompem com esse repertório mais recorrente de crenças na função
> policial e o colocam em dúvida. Para esses juízes, "fé cega" tem
> consequências danosas não apenas para as partes envolvidas diretamente
> com o processo, mas para o próprio juiz, para o sistema de justiça e
> para a sociedade. Quando se investe tamanha credibilidade aos
> policiais, coloca-se em risco o papel fiscalizatório de órgãos como
> Ministério Público e Poder Judiciário, ampliando o poder da polícia
> [@jesus2016]. Segundo um dos juízes entrevistados por Jesus em sua
> pesquisa: "eu vou estar na função de julgador e preciso atuar na
> garantia de direitos. Se no final tem elementos para que ele \[pessoa
> acusada\] seja condenado, ele vai ser condenado" [@jesus2016, p. 206].

Ao descrever essas possibilidades, as pesquisas de @semer2019 e Jesus
demonstram, assim como pretendemos mostrar com o presente artigo, que o
campo jurídico é um universo heterogêneo, apesar de aparentemente
apresentar decisões por vezes majoritárias com relação à tendência de se
privilegiar a narrativa policial como central para a condenação de
pessoas por tráfico de drogas. Nos Estados Unidos, Anna Lvovsky (-@lvovsky2021)
mapeou e sistematizou alguns casos em que a palavra dos policiais, seus
saberes e sua expertise foram colocadas em xeque nos tribunais. A autora
identifica duas concepções sobre o tema mobilizadas por magistrados e
magistradas e aponta as principais consequências de cada uma delas.
Segundo Lvovsky, há caminhos para que os operadores do direito sejam
mais exigentes com as provas apresentadas por agentes de segurança e
estes partem de um dos entendimentos que já circulam, mesmo que de
maneira minoritária. Parece importante, portanto, identificar os
argumentos que já circulam nos casos de absolvição e desclassificação e
verificar se estes operam como possíveis "pontos de fuga" da atuação
majoritária do judiciário.

Entre as inquietações que surgem ao estudar os processos judiciais de
casos de tráfico de drogas e analisar como os atores do sistema de
justiça criminal[^11] recepcionam as narrativas policiais, uma delas nos
chamou a atenção: o que poderia explicar que algumas das acusações de
tráfico tivessem como desfecho a absolvição ou a desclassificação para
porte com finalidade de uso, contrariando, portanto, as alegações feitas
pelos agentes de segurança que realizaram a prisão?

Apenas com base na leitura das sentenças não é possível verificar com
exatidão uma variável que explique o que motivou a desclassificação ou
absolvição dos casos. Fatores como a classe social, a raça e até mesmo
o gênero da pessoa acusada podem ter influenciado tais decisões. A
seletividade racial do sistema de justiça criminal fica evidente ao
olharmos quem são as pessoas condenadas e presas. Trabalhos como o de
Ana Luiza Pinheiro Flauzina (2006), por exemplo, demonstram que a
operação do sistema de justiça criminal brasileiro não se descolou
completamente das formas de extermínio racial colocadas em marcha
durante a escravidão. Nesse mesmo sentido, ao olhar para os Estados
Unidos, Michelle Alexander (-@alexander2017) sustenta que o encarceramento em
massa é uma forma atualizada de manter a segregação racial naquele
país. Dina Alves (2017), por sua vez, em pesquisa etnográfica de
espaços prisionais e judiciais, relata as dissonâncias entre as
representações, feitas por juízes brancos, das mulheres negras
criminalizadas: uma mulher "*negra, sem dentes, homossexual,
carroceira e vivendo nas ruas da cidade*" foi condenada por conta de
sua "*temibilidade*" [@alves2017, p. 112].

Contudo tais análises não são, em regra, perceptíveis apenas a partir
de uma análise documental das decisões judiciais, que não registram
informações como, por exemplo, a raça/cor da pessoa acusada. Para
ampliar a compreensão sobre os fatores que ensejam uma absolvição ou
uma desclassificação, parecem ser necessários não somente trabalhos
que investiguem por que juízes e juízas condenam (com maior
frequência) pessoas negras, mas também se (e por que) eles são mais
lenientes com pessoas brancas criminalizadas[^12]. Além disso, assim
como fatores raciais, sociais e de gênero, outras circunstâncias
também concorrem para motivar os resultados dos procedimentos
judiciais. Independentemente dos motivos que podem levar a uma
absolvição ou desclassificação, nossa hipótese inicial é de que,
nesses casos, os juízes e juízas mobilizam algum tipo de justificativa
para afastar os relatos trazidos ao processo pelos policiais.

Considerando isso, também temos como hipótese que um dos elementos que
pode surgir nos casos analisados é a tendência em haver mais
desclassificações/absolvições nos casos de prisão em flagrante efetuadas
por policiais civis. Essa hipótese estaria relacionada à qualidade dos
casos, em que policiais civis tenderiam a realizar flagrantes para
cumprirem a "meta" do mês, sem a preocupação de reunir mais provas aos
casos ~~(Alves *et al.*, 2018)~~. Também parece haver uma maior
"desconfiança" dos atores do sistema de justiça com relação ao trabalho
da polícia civil do que quanto ao da polícia militar [@silvestre2014;
@machado2015; @costa2015; @semer2019]. Ainda nessa chave,
poderíamos dizer que os atores do sistema de justiça criminal avaliam as
narrativas policiais com maior criticidade e relativizaram sua
centralidade para a tomada de decisão ou porque as versões foram
consideradas contraditórias, ou porque consideraram que apenas o
testemunho dos policiais que efetuaram a prisão não era suficiente para
ensejar uma condenação por tráfico de drogas.


# Recorte de pesquisa e metodologia adotada

Com o objetivo de investigar o tratamento dado aos depoimentos dos
policiais nos casos em que o desfecho processual foi a absolvição da
pessoa acusada ou a desclassificação para porte para uso de drogas, a
pesquisa lançou mão de algumas estratégias metodológicas. De um lado,
realizamos um levantamento bibliográfico abrangente sobre as decisões
judiciais nos casos de tráfico de drogas, com especial atenção para os
trabalhos que discutem o papel dos agentes de segurança nessa intrincada
teia judicial. Buscamos identificar trabalhos tanto das ciências
sociais, quanto do direito, sem distinção em relação ao momento
processual enfocado por cada um deles.

Além disso, mobilizamos dados de duas pesquisas. A primeira correspondeu
a um estudo realizado em 667 autos de prisão em flagrante (APF) de
tráfico de drogas de novembro, dezembro de 2010 e janeiro de 2011
referentes a casos da cidade de São Paulo [@jesus2011]. A segunda
correspondeu a 74 sentenças de pessoas acusadas de tráfico de drogas
publicadas entre outubro e dezembro de 2017 [@amaral2018][^13]. Nessa
segunda amostra, só foram considerados os casos em que o processo se
iniciou a partir de uma denúncia anônima[^14]. Desse material extraímos
os processos que tiveram como desfecho a desclassificação ou a
absolvição dos/as acusados/as, totalizando 38 documentos. Elaboramos uma
planilha para a coleta das seguintes informações nesses autos: nº do
processo, ano, autor da prisão, quantidade de drogas, nome das
autoridades envolvidas nos casos, manifestação do Ministério Público,
por quem foi defendido (defensor ou advogado particular), decisão do
juiz, o que se fala sobre narrativa policial e o que pareceu influenciar
o resultado (contradições nos testemunhos policiais, quantidade da droga
etc.). Coletamos também fragmentos das sentenças que exemplificam as
justificativas apresentadas pelos atores do sistema em suas decisões de
desclassificação ou absolvição do processo de tráfico de drogas.

Realizamos uma análise mais qualitativa, observando as manifestações dos
representantes do Ministério Público e dos magistrados. Outra análise
interessante a ser realizada qualitativamente nesses processos se refere
ao fato de serem de períodos com relativo intervalo de tempo entre um e
outro. O primeiro realizado em 2011 e o segundo em 2017, um intervalo de
sete anos, sendo possível analisar em que medida os argumentos se
repetiam ao longo desse tempo ou se o tempo transcorrido surtiu alguma
alteração quanto à apresentação de certos argumentos. Destacamos,
contudo, não se tratar de análise longitudinal, mas de análises de duas
pesquisas realizadas em tempos diferentes.

# Resultados: análises dos casos de desclassificação e absolvição

A análise dos casos nos indica que não é possível fazer uma
generalização de que uma determinada variável explique as decisões que
resultam em absolvição ou desclassificação, isso porque os argumentos
que apareceram foram tanto com relação à pouca quantidade de drogas
apreendidas em alguns casos, quanto em relação à dificuldade em se
estabelecer uma conexão entre a droga encontrada (mesmo quando em
quantidade considerável) e a pessoa acusada, sobretudo com relação à
intenção do acusado de vender o entorpecente.

As análises qualitativas das sentenças nos indicaram três situações
evidenciadas nos argumentos dos juízes em suas sentenças em que o
desfecho de desclassificação ou absolvição acontecem: (a) os juízes
falam da fragilidade das provas, sem mencionar as narrativas policiais;
(b) os juízes falam das narrativas policiais, destacando que não devem
ser desmerecidas, mas apontam que não são suficientes para provar que a
droga iria ser comercializada pela pessoa presa; (c) os juízes criticam
as contradições presentes nas narrativas policiais diretamente e dizem
que condenar o acusado com base apenas nesses testemunhos fragiliza o
processo. Abaixo trazemos exemplos dessas três situações descritas.

## (a) Prova frágil, mas não mencionam o testemunho policial

> Preso disse ser usuário, as drogas foram encontradas no chão, não
> havendo como saber se o acusado era de fato o dono das substâncias.
> \[\...\] sem prova do elemento subjetivo do tipo, para a sociedade,
> ainda é melhor arquivar um inquérito, preservando-se a possibilidade
> de reabri-lo com *provas melhores*, do que propor ação penal com base
> precária, que torne provável a absolvição. (Processo 05010087066-0 --
> grifo nosso)
>
> \[\...\] as investigações realizadas não evoluíram para plano
> tangível, no sentido de demonstrar que a investigada era a responsável
> pelo imóvel onde os adolescentes praticavam a narcotraficância, muito
> menos que a consentia \[\...\] sem prova do elemento subjetivo do
> tipo, para a sociedade, ainda é melhor arquivar um inquérito,
> preservando-se a possibilidade de reabri-lo com *provas melhores*, do
> que propor ação penal com base precária, que torne provável a
> absolvição. (Processo 05010087551-3 -- grifo nosso)
>
> Não se pode condenar com base em presunções e meros indícios colhidos
> na fase investigatória. São necessárias provas firmes, seguras, da
> autoria e materialidade dos delitos, e especialmente da verificação da
> conduta dolosa, quando exigida pelo tipo penal, o que no caso dos
> autos não se verifica. *O conjunto probatório, no presente caso, não
> sustenta uma condenação criminal. Restou claro que o traficante era
> outra pessoa que a ré.* \[\...\] Consideradas as graves repercussões
> de uma condenação, há de se ter as maiores cautelas na apreciação do
> conjunto probatório e verificação da responsabilidade criminal, *sendo
> preferível o risco de absolver eventuais culpados à mais ligeira
> possibilidade de condenar um inocente.* (0033038-57.2017 -- grifo
> nosso)

## (b) Prova frágil e mencionam o testemunho policial sem desmerecê-lo

> Os dois policiais militares que realizaram as duas abordagens e a
> prisão do réu, ouvidos nesta data, apresentaram *depoimentos afinados
> e seguros* \[\...\] O réu disse aos policiais que era viciado e que as
> drogas eram para o seu uso próprio. \[\...\] Os policiais não
> presenciaram o réu comercializando os entorpecentes e nem mesmo estava
> no ponto de tráfico. (Processo 05011000573-2 -- grifo nosso)
>
> Sem a pretensão de *desqualificar os testemunhos dos Policiais
> Militares, prestados com coerência*, a negativa apresentada pelo
> acusado não foi refutada por seus depoimentos, pois narraram apenas a
> apreensão das drogas encontradas na posse do acusado, depois da
> tentativa de fuga, que estavam no interior da bolsa que trazia presa
> junto à cintura; mas não narraram qualquer ato indicativo de comércio,
> como se o acusado entregasse alguma coisa a outrem e dele recebesse
> algo, nem foram encontrados dinheiro ou petrecho para uso de drogas.
> (Processo 05011004437-1 -- grifo nosso)
>
> Não se trata de *desqualificar* a relevante função pública preventiva
> desempenhada pelos policiais civis e militares que, presumidamente,
> cumprem a lei. Entretanto, pelo acima exposto, no caso em tela,
> remanesce fundada dúvida quanto à real participação do denunciado na
> prática dos crimes de tráfico de entorpecentes e porte ilegal de arma
> de fogo, não havendo como condená-lo por tais crimes exclusivamente em
> razão de sua presença e revista quando da abordagem efetuada pelos
> policiais. (Processo 0041542-52.2017 -- grifo nosso)
>
> Realmente, embora a prova oral produzida pela acusação decorra
> exclusivamente dos depoimentos daqueles dois policiais militares, *a
> mesma é idônea e digna de crédito*, pois ambos afirmaram expressamente
> ao magistrado que sequer conheciam o denunciado até a data dos fatos,
> do que se conclui que não teriam qualquer razão para injustamente
> incriminá-lo. (Processo 0097020-79.2016 -- grifo nosso)

##  (c) Mencionam o testemunho policial e apontam contradições e fragilidades

> Os depoimentos dos policiais militares não demonstram com a segurança
> exigida que o réu estivesse ali comercializando a substância
> entorpecente que trazia consigo ou que a entregaria de qualquer forma
> ao consumo de outrem. \[\...\] *Os policiais sequer mencionaram em
> juízo a confissão informal do réu no ato da abordagem.* (Processos
> 05010090968-0 -- grifo nosso)
>
> A versão dos policiais é *confusa, o que lhes tira a credibilidade*.
> \[\...\] Assombroso como alguns policiais se lembram somente de parte
> dos acontecimentos que vivenciaram, esquecendo-se de situações muito
> relevantes o que muitas vezes dá ensejo a paradoxos incríveis. Nestas
> situações raramente se lembram de circunstâncias que favorecem a
> pessoa que detiveram. \[\...\] Ao que parece a versão do réu é a mais
> plausível. (Processo 05011002209-2 -- grifo nosso)
>
> Torna-se impossível, no caso, embasar um decreto condenatório nos
> *imprecisos e contraditórios depoimentos policiais*, devendo
> prevalecer a versão exculpatória apresentada pelo acusado \[\...\] Tal
> versão mostra-se crível e deve ser prestigiada, mormente porque os
> policiais civis ouvidos em juízos encontraram em *contradição* em
> pontos relevantes. (Processos 05010091324-5 -- grifo nosso)
>
> Os policiais ouvidos nesta data recordaram-se pouco da ocorrência,
> sendo que apenas o policial D. informou alguma coisa a respeito da
> mesma, no entanto, *informou fatos que sequer constam da denúncia, não
> dando o devido suporte para um decreto condenatório*. \[\...\]
> *Policiais militares acometidos de amnésia, um nada se lembrava, o
> outro lembrou-se de fato diverso*. De toda forma, depoimentos que, se
> já eram um tanto insatisfatórios na fase policial, não se prestam, sob
> o contraditório, a embasar mínima certeza de autoria do tráfico de
> entorpecentes. (Processo 05010102812-1 -- grifo nosso)

# Discussão: "presunção absoluta" versus "presunção relativa"

Essas três situações mostram um ponto em comum, em todas elas os juízes
afirmam que não é possível condenar a pessoa acusada com as provas
reunidas no processo, sobretudo com relação à traficância. É possível
verificar uma certa "métrica", digamos assim, do que precisaria estar
presente nos autos para se comprovar a intenção da pessoa na venda da
droga: a apreensão de um usuário dizendo ter comprado drogas com ela;
uma versão do testemunho policial em que fique mais evidente o ato de
venda do entorpecente por parte do acusado; presença de "confissão
informal"; existência de outros elementos, como dinheiro trocado ou
variedade de tipos de drogas etc. É preciso, mais que tudo, "visualizar
o comércio". Há um reconhecimento, por parte desses magistrados, de que
a fragilidade das provas inviabiliza a condenação do réu.

Esse ponto torna-se relevante se pensarmos que, na grande maioria dos
casos, não há nenhum tipo de investigação realizada: cerca de 89% das
sentenças analisadas por @semer2019, por exemplo, eram fruto de prisões em
flagrante, enquanto em só 10% dos casos houve algum tipo de investigação
prévia [@semer2019, p. 158]. Entre os Estados analisados pelo autor,
São Paulo era o que tinha menor percentual de investigações (somente 6%
dos casos). Na pesquisa de 2011, apenas 4% dos flagrantes haviam sido
resultado de investigação policial. Essa é também a conclusão de @ribeiro2017, que analisaram dados do
Tribunal de Justiça de Minas Gerais (TJ-MG) entre 2008-2015 e
identificaram que mais de 63% dos casos processados por tráfico de
drogas se originaram de um flagrante, o que contribui para o que eles
denominaram de "justiça em linha de montagem", em que o sistema é
operacionalizado em uma lógica de produção, de produtividade [@sapori1995]. O trabalho de @romano2021, também baseado
em decisões do TJ-MG, demonstra, inclusive, que os flagrantes de casos
de tráfico de drogas são distintos dos de outros crimes. Nos primeiros,
não há outras testemunhas além dos policiais em 96,7% dos casos,
enquanto em flagrantes por outros crimes isso só ocorre em cerca de 31%
dos casos; além disso, o percentual de pessoas desarmadas em flagrantes
por tráfico é de 90%, enquanto nos flagrantes de outros crimes o número
não passa de 74% [@romano2021, p. 721]. Se via de regra não há
nenhum tipo de apuração sobre a situação em que ocorreu o suposto crime,
faz sentido que as provas sejam consideradas frágeis. O que surpreende é
que somente em tão poucos casos isso seja admitido pelos juízes e
juízas.

Ao analisar as sentenças que tiveram como desfecho um resultado
absolutório, buscando compreender o prestígio da presunção de inocência,
@semer2019 descreve outro ponto interessante entre os dados reunidos
em sua pesquisa: a média de réus por processo era de 1,52, enquanto
considerando apenas os que resultaram em absolvição era de 2,48. Esse
dado confirma o que vimos em nossa pesquisa, que um dos acusados pode
"assumir" a responsabilidade da droga, isentando os demais réus. Essa
constatação, aliada ao achado de que, em algumas sentenças analisadas,
nem se menciona o testemunho policial, demonstrou que nossa hipótese
inicial, de que nesses casos haveria necessariamente a mobilização de
alguma justificativa para afastar a narrativa policial, era falsa.

Os dados compilados nos remetem a uma análise realizada por  ~~Vivian
Calderoni (2014)~~, no sentido de que é possível identificar duas linhas
de entendimento sobre a recepção de testemunhos de agentes públicos
pelos juízes: a) uma que entende que tais agentes apresentam "fé
pública", têm credibilidade, "presumida legitimidade de seus atos" e
"presumida veracidade", o que poderia ser classificado como "presunção
absoluta" (*jure et de jure*); b) uma outra que entende que o testemunho
do agente público precisa ser avaliado a partir de uma série de
elementos presentes no processo, o que poderia ser classificado como
"presunção relativa" (*jure et tantum*) ~~(Calderoni, 2014, p. 116)~~. A
análise empírica dos processos de tráfico de drogas que resultaram em
desclassificação ou absolvição nos permite ver com maior frequência uma
"presunção relativa" por parte dos juízes. Portanto, se o magistrado ou
magistrada for mais ligado a essa linha, é provável que as contradições
revelem a fragilidade da prova e ele ou ela opte por absolver ou
desclassificar o acusado, que passa a ser considerado usuário, e não
traficante. Nesses casos, os juízes utilizam jurisprudência como a
descrita abaixo:

> Como testemunhas, somente foram ouvidos os policiais, que confirmaram
> os fatos da denúncia. Logo, para a condenação, somente há como base
> seus depoimentos. Não é possível fazê-lo. Não se trata, aqui, de
> tentar revestir de falsidade os depoimentos dos policiais, *mas é
> inegável que seus depoimentos, isolados não bastem para alicerçar uma
> condenação*. Julio Fabbrini Mirabete, acerca do tema: "Também se
> discute o valor do testemunho de policiais, quando são os únicos
> apresentados pela acusação. Já se tem argumentado, *principalmente nos
> crimes referentes a tráfico de entorpecentes, que a condenação não se
> pode basear apenas no depoimento dos policiais, que têm interesse em
> dizer legítimas e legais as providências* tomadas por eles na fase de
> Inquérito" ~~(grifei)~~ (Julio Fabbrini Mirabete, *Processo Penal*, 8ª
> ed., São Paulo: Saraiva, 1997, p. 306). Nesse sentido é a
> jurisprudência: Não há vedar que policiais prestem depoimentos a
> respeito de diligências que efetuaram, entretanto, esta não é sua
> função precípua e, por mais idôneo que seja o miliciano, por mais
> honesto e correto, ao servir como testemunha, no fundo *está
> procurando ratificar a sua própria conduta, o que juridicamente não é
> admissível.* (Processo nº 05010097970-0 -- grifos nossos)

Aqui, é interessante pensar em alguns fatores que explicam o motivo da
crítica direta à narrativa policial ser minoritária, mesmo nas sentenças
absolutórias ou desclassificatórias, ainda mais naquelas coletadas em
2018. @semer2019, por exemplo, aponta que, uma vez que as provas que derivam
de tais narrativas são o pilar de sustentação dos casos, admitir
expressamente suas contradições "é uma verdade dolorosa demais a quem se
incumbe de agir em nome da ordem: afastar o depoimento dos policiais
pode significar absolvições com frequência" [@semer2019, p.195]. A
prática de absolver com certa frequência, por sua vez, tem um custo:
pode resultar em investigações e procedimentos disciplinares contra o
juiz ou juíza que adota posicionamentos contramajoritários. Para além
das punições institucionais[^15], esse posicionamento também afasta tais
profissionais do que @semer2019 chama de "*inner ring*" [@semer2019, p. 278]
 ou grupo de colegas. O autor trabalha com a hipótese de que o
desejo de manutenção nesse círculo pode motivar os juízes a usarem, com
tanta frequência, precedentes do próprio tribunal em que trabalham --
mais do que usam, por exemplo, decisões de tribunais superiores como o
STF ou STJ -- como fundamento de suas sentenças. Vale registrar que o
tema mais encontrado por @semer2019 na jurisprudência utilizada nas sentenças
por ele analisadas foi o da validade do depoimento policial, que surgiu
em mais de 35% dos casos que mencionam outras decisões judiciais [@semer2019, p. 275].

Alguns estudos[^16] sobre o Poder Judiciário brasileiro descrevem um
campo de divergências internas muito profícuo para entendermos por
que, em alguns casos, os/as juízes apresentam posturas mais
questionadoras e focadas na presunção da inocência. Parte da
literatura identifica esses perfis como mais "garantista"[^17],
enquanto os magistrados mais "linha dura" são identificados como mais
"punitivistas" (~~Carvalho (2008)~~, [@bento2013; @custodio2021; @estrela2021]). Alguns autores destacam que muitos juízes têm tomado para
si o papel de preservar a segurança pública, utilizando para isso a
prisão como recurso, reiterando discursos que reforçam o pânico moral
e a ideia de uma sociedade aterrorizada, sobretudo com relação às
questões relacionadas às drogas [@valois2016; @semer2019; @casara2015]. Contudo apontam para juízes que, apesar de minoritários no
campo da justiça penal, tomam decisões buscando embasá-las na garantia
de direitos e na presunção de inocência. Como mencionado em uma das
decisões citadas acima: é "*preferível o risco de absolver eventuais
culpados à mais ligeira possibilidade de condenar um inocente*"*.*
(0033038-57.2017 -- grifo nosso)

Algumas pesquisas, como a da @conectas2018 e de @custodio2021,
mostram que há uma tendência de juízes se alinharem a decisões
majoritárias com relação a certas temáticas mais polêmicas, sobretudo
sobre drogas, por comodismo, por um lado, e por receio de sofrerem
represálias dentro da carreira, por outro. Alguns casos exemplificam
essas situações, como o da desembargadora Kenarik Boujikian, que
recebeu pena de censura[^18] após decidir pela soltura de pessoas
presas em regime provisório por prazo superior aos das penas a elas
impostas nos processos, e do juiz Roberto Corcioli, que sofreu
representações em razão das decisões proferidas. Ambos foram
inocentados pelo Conselho Nacional de Justiça, contudo tiveram que
atravessar um longo percurso até esse resultado. A pesquisa da
@conectas2018 analisou justamente como mecanismos de controles
institucionais internos acabam favorecendo uma tendência focada numa
atuação penal punitivista por parte desses operadores, resultando num
maior encarceramento penal. Mostram que há fragilidades com relação à
garantia de independência da atuação dos juízes e que isso impacta em
suas decisões processuais:

> Com relação à aparente concentração de magistrados e promotores com
> perfil punitivista atuando na área criminal, alguns entrevistados
> mencionaram que isso pode estar relacionado à própria tradição do
> campo, desde a doutrina, ao ensino da matéria penal nas faculdades de
> direito, ser um reduto de uma abordagem conservadora do direito. Além
> disso, tradicionalmente, dentro dessas instituições o entendimento do
> que é a atuação criminal sempre foi punitivista e conservador \[\...\]
> No entanto, parece que há outros fatores, ligados à fragilidade das
> garantias de inamovibilidade e independência funcional, que podem
> explicar essa aparente concentração de magistrados e promotores que
> atuam na área criminal com um viés punitivista/conservador, como o
> próprio funcionamento desses órgãos criminais, inclusive com a
> possibilidade de escolha por parte da cúpula do TJ-SP de quais perfis
> de juízes ocupariam esses postos, como veremos em outro tópico deste
> relatório (@conectas2018, p. 21).

A pesquisa da @conectas2018 apresenta um ponto importante a se
considerar: há juízes que ainda não gozam da garantia de
inamovibilidade, como é o caso de substitutos e auxiliares, e isso
acaba trazendo fragilidade nas relações internas, na sua atuação e,
sobretudo, no conteúdo de sua decisão. Haveria um tipo de "controle
sutil" da forma de atuação desses juízes, ou seja, se atuarem em
desacordo com aquilo que deles é esperado, podem ser removidos para
outra Vara ou Comarca. Portanto, para não sofrerem esse tipo de
situação, os magistrados se submeteriam ao controle interno, passando
por um "autocabresto" ou "autocensura" [@conectas2018, p. 50].

Nesse sentido, é possível identificarmos um elemento importante que
pode nos ajudar a compreender por que os juízes tendem a seguir
decisões majoritárias, e não as minoritárias, no interior do campo
jurídico. Decidir por desclassificar ou absolver um acusado por crime
de tráfico de drogas pode gerar um ônus pessoal e uma pressão
institucional. Segundo um dos magistrados entrevistados na pesquisa da
@conectas2018, quando um juiz "garantista" foi designado para o
Departamento de Inquéritos Policiais (DIPO) do Fórum Criminal da
cidade de São Paulo, a primeira coisa que ele teria comentado é que
"pisaria no freio" nas suas decisões, "para se adequar ao perfil dos
juízes que trabalham naquele departamento que, segundo a sua opinião,
eram mais conservadores". [@conectas2018, p. 51]

Os dados explicitam muitas das questões levantadas por autores como
@lima1991 e @mendes2012. De acordo com os autores, no campo
processual, a busca pela verdade é vista como uma reconstrução
histórica dos fatos, com o objetivo de determinar o que aconteceu,
como se deu o evento, se constitui crime e quem foi o responsável,
para que se possa proceder ao julgamento [@badaro2003]. No direito
brasileiro, esse processo é conhecido como a busca da "verdade real"
[@mirabete2007; @capez2003; @greco1997], diferenciando-se das
ciências, em que a verdade é construída pelo consenso entre os
participantes, e do processo civil, no qual as partes são responsáveis
por produzir as provas e o juiz se limita a decidir com base nelas
[@lima1991].

No princípio da "verdade real", o juiz exerce um papel central, com base
no seu "livre convencimento", que lhe permite selecionar e valorar as
provas apresentadas. Esse conceito confere ao magistrado poderes
inquisitórios e grande discricionariedade no processo penal [@lima1991;
@lima2004; @mendes2008]. Regina Mendes [-@mendes2012], em sua pesquisa, discute
criticamente o "livre convencimento" e como ele é um fator determinante
para a legitimação de decisões judiciais, muitas vezes resultando em
julgamentos desiguais para casos semelhantes [@mendes2012]. A liberdade
que o juiz tem de avaliar as provas, sem a necessidade de se basear
exclusivamente nos elementos trazidos pela investigação, pode, segundo
Mendes, criar um espaço para decisões influenciadas por subjetividades e
seletividades, o que reforça desigualdades no sistema de justiça.

No caso específico de crimes de tráfico de drogas, além do entorpecente
apreendido e atestado pelo Instituto de Criminalística, o testemunho dos
policiais que efetuaram a prisão é amplamente aceito pela jurisprudência
e doutrina como prova legítima [@lima2004; @mendes2012]. @mendes2012
enfatiza que o "livre convencimento" do juiz permite que inquéritos
policiais, muitas vezes com lacunas ou indícios frágeis e resultantes de
uma prisão em flagrante, como indicado acima, possam adquirir o mesmo
"estatuto de verdade" que outras provas produzidas judicialmente
[@mendes2012].

A pesquisa de @mendes2012 revela que o princípio do "livre convencimento" não
apenas autoriza o juiz a decidir de acordo com sua consciência, limitado
pelo que consta nos autos, mas também sustenta a ideia de que a
jurisdição exerce um papel pacificador na sociedade. No entanto, essa
liberdade decisória, conforme sua análise, tende a reproduzir
desigualdades e a naturalizar uma distribuição desigual de justiça,
mascarando sob o manto da imparcialidade uma série de filtros, disputas
e seleções que compõem a verdade jurídica [@mendes2012].

> Essas pesquisas nos revelam, portanto, que há mais elementos que
> precisam entrar na análise desses processos que resultam em
> condenação, desclassificação ou absolvição das acusações de tráfico de
> drogas. É preciso, entre outras medidas, olhar a forma como o campo
> jurídico pressiona seus agentes para a tomada de decisões.

# Considerações Finais

Uma das hipóteses que tínhamos com relação à desclassificação e
absolvição dos casos de tráfico de drogas era a de que os flagrantes
efetuados pela polícia civil tendiam a sofrer mais questionamentos por
parte dos atores do sistema de justiça do que aqueles realizados pela
polícia militar. Os dados nos indicam que, de maneira absoluta, os casos
envolvendo policiais militares eram mais questionados do que os
envolvendo policiais civis. No entanto, por representarem a maioria das
prisões em flagrantes, esse dado na verdade tem que ser lido de outra
forma. Ao compararmos proporcionalmente como eram distribuídos os
argumentos dos atores do sistema de justiça quanto ao testemunho
policial, percebemos que os policiais civis sofriam um maior
questionamento com relação às prisões em flagrantes efetuadas do que os
policiais militares. Ou seja, esses dados indicam uma maior desconfiança
dos atores da justiça com relação aos policiais civis do que com os
policiais militares, corroborando algo que já foi apontado por parte da
literatura que trabalha com a relação entre as instituições policiais e
o sistema de justiça criminal [@silvestre2014; @machado2015;
@costa2015; @semer2019].

Assim, apesar de esse dado ser relevante, ele não é suficiente para
compreendermos por que, mesmo nos casos em que policiais militares são
os autores da prisão, juízes decidem pela desclassificação para uso ou
mesmo absolvição. Para tentarmos aprofundar a resposta a essa questão,
ampliamos o escopo da análise a partir da sistematização das leituras
das sentenças, cruzando com reflexões de outras pesquisas. Esse
exercício nos permitiu dizer que identificamos duas perspectivas
interessantes quando analisamos esse material. A primeira tem relação
com os argumentos mobilizados pelos magistrados em suas decisões e as
justificativas que utilizam para desclassificar ou absolver as pessoas
apreendidas por acusação de tráfico de drogas. Identificamos três
categorias decisórias: as que consideram a prova frágil, mas não
mencionam o testemunho policial; as que consideram a prova frágil e
mencionam o testemunho policial sem desmerecê-lo; e as que mencionam o
testemunho policial e apontam contradições e fragilidades nessas
narrativas. A segunda perspectiva de análise é a que leva em conta o
campo de disputas interno no poder judiciário, sobretudo na justiça
criminal. A literatura aponta que há divergências entre os magistrados
sobre a forma como devem recepcionar as narrativas policiais, mostrando
que há uma pressão entre os pares para que os juízes decidam de acordo
com a posição majoritária, que entende que o policial, por exemplo,
conta com a "presunção de veracidade" com relação aos seus relatos da
prisão em flagrante que realizou, afastando, com isso, qualquer tipo de
dúvida ou questionamento com relação ao seu testemunho. Isso pode
indicar que os juízes passaram a ter em seus argumentos outras
estratégias discursivas para desclassificar ou absolver uma pessoa
acusada por tráfico de drogas sem criticar diretamente o testemunho
policial. Talvez porque uma crítica à polícia, sobretudo à polícia
militar, gere algum "custo" institucional, algum conflito entre os
órgãos da polícia e do sistema de justiça, como apontado pelas pesquisas
citadas.

Apesar desses desafios e pressões internas, ou mesmo sem fazer uma
crítica direta ao trabalho policial, juízes têm se posicionado num campo
identificado como "garantista" e adotado posturas mais criteriosas com
relação à recepção de testemunhos policiais, o que demonstra que o campo
jurídico é um universo heterogêneo, apesar de aparentemente apresentar
decisões por vezes majoritárias com relação à tendência de se
privilegiar a narrativa policial como fundamental para a condenação de
pessoas por tráfico de drogas. Parece importante, portanto, identificar
os argumentos que já circulam nos casos de absolvição e desclassificação
e verificar se estes operam como possíveis "pontos de fuga" da atuação
majoritária do judiciário.

As decisões de tribunais superiores também demonstram como a questão da
narrativa dos policiais nos casos criminais tem sido disputada. @hirata2021, por exemplo, relatam como
a produção de dados sobre a letalidade das operações policiais no Rio de
Janeiro informou a Ação de Descumprimento de Preceito Fundamental (ADPF)
n. 635, conhecida como "ADPF das Favelas"[^19], analisada recentemente
pelo Supremo Tribunal Federal (STF). A sistematização e o registro de
informações sobre a violência desse tipo de ação, realizados por
organizações da sociedade civil, ajudaram a matizar o retrato geralmente
feito pelas forças de segurança pública sobre a necessidade e a
proporcionalidade do uso de força nessas situações[^20]. A decisão da
ADPF acolheu diversas das solicitações feitas a fim de implementar
mecanismos de controle das ações policiais e diminuir seu grau de
violência. Trata-se, portanto, de decisão que reconheceu que a narrativa
das polícias sobre esse tipo de situação não é totalmente verdadeira e
pode ser questionada.

No mesmo sentido, mas voltada para a atuação do dia-a-dia da polícia,
está a recente decisão do Superior Tribunal de Justiça (STJ) que
considerou ilegal a abordagem pessoal baseada apenas na alegação dos
policiais de identificação de "atitude suspeita"[^21]. No voto, o
Ministro Rogério Schietti Cruz sustenta que devem ser exigidos
"elementos sólidos, objetivos e concretos", que vão além da simples
intuição, para que policiais realizem abordagens pessoais. Por fim,
também o *Manual sobre Tomada de Decisões na Audiência de Custódia*,
elaborado pelo Conselho Nacional de Justiça (CNJ) em 2020, recomenda que
"o juiz ou juíza deve sempre contrapor a versão trazida pela polícia à
versão da pessoa custodiada", em especial nos casos de acusação por
tráfico de drogas [@brasil2020, p. 46].

@lima1991 e @mendes2012 fornecem uma base teórica crucial para
entender os dados analisados sobre a desclassificação e absolvição de
casos de tráfico de drogas. @lima1991 destaca a diferença entre a
"verdade real" e a "verdade formal", explicando como a subjetividade e
as escolhas dos juízes influenciam a decisão judicial. @mendes2012, por sua
vez, critica o princípio do "livre convencimento", enfatizando como ele
pode legitimar decisões desiguais e influenciadas por subjetividades,
especialmente no contexto do testemunho policial. Esses autores ajudam a
interpretar os dados ao mostrar que, apesar da aparente predominância de
decisões favoráveis a testemunhos policiais, existe uma desconfiança
maior em relação aos policiais civis em comparação com os militares.
Além disso, @mendes2012 sugere que, mesmo na ausência de críticas diretas aos
policiais, os juízes adotam estratégias discursivas para desclassificar
ou absolver réus, evidenciando um campo jurídico heterogêneo em que as
práticas judiciais são moldadas por pressões internas e externas. As
decisões judiciais refletem uma complexa interação entre práticas
policiais, percepções judiciais e disputas institucionais, revelando
nuances importantes na aplicação da justiça criminal. No entanto essa
mobilização de argumentos, que têm o enquadramento do "livre
convencimento" do juiz, tanto pode deixar um campo aberto para decisões
mais conservadoras e punitivistas, engajadas nas narrativas policiais
como fundamento para os desfechos dos casos, quanto para decisões mais
críticas a essa narrativa, abrindo possibilidades para desclassificação
ou absolvição de casos em que não está clara a definição entre usuário e
traficante. Desse modo, há uma disputa interna ao campo judiciário, em
que é possível vislumbrar interpretações diversas com relação à
centralidade da narrativa policial para a decisão dos casos.

Os exemplos acima indicam que há caminhos, dentro da própria prática
jurídica, que não posicionam a narrativa policial como tão central para
a solução de certos casos. Trata-se, ao contrário, de tentativas de
exercer maior controle sobre as práticas de tais agentes públicos.
Enxergar o judiciário como um campo de disputas permite complexificar as
análises sobre o tema e jogar luz nas linhas de força que, mesmo que de
início pouco evidentes, circulam e compõem as operações do sistema de
justiça criminal brasileiro.








<!-- Notas de rodapé  -->
[^1]: Pesquisadora do Núcleo de Estudos da Violência da Universidade de
    São Paulo (NEV-USP). Professora do Departamento de Sociologia da
    Universidade Federal de São Carlos (UFSCar), SP, Brasil. E-mail:
    <gorete.marques@gmail.com>; Orcid:
    <https://orcid.org/0000-0003-2667-8736>.

[^2]: Mestre pelo Programa de Pós-Graduação em Sociologia da
    Universidade de São Paulo (USP). E-mail: <mariana.amaral@usp.br>;
    Orcid: <https://orcid.org/0000-0003-1634-8709>.

[^3]: As informações podem ser acessadas online por meio do portal
    SISDepen. Disponível em:
    https://www.gov.br/depen/pt-br/servicos/sisdepen. Acesso em: 01 abr.
    2022.

[^4]: Instituto Brasileiro de Geografia e Estatística (IBGE). Pesquisa
    Nacional por Amostra de Domicílios Contínua trimestral - população
    por raça ou cor. Disponível em:
    https://sidra.ibge.gov.br/tabela/6403. Acesso em: 01 abr. 2022.

[^5]: Sobre o reconhecimento do "estado de coisas inconstitucional" do
    sistema prisional brasileiro, bem como suas limitações, ver: GLEZER,
    Rubens; ALMEIDA, Eloísa Machado de. Decide, mas não muda: stf e o
    estado de coisas inconstitucional. Jota. 09 set. 2015. Disponível
    em: https://www.jota.info/artigos/decide-mas-nao-muda-stf-e-o-estado-de-coisas-inconstitucional.
    Acesso em: 19 nov. 2024.

[^6]: Mais recentemente, por exemplo, em nota sobre a "situação das
    pessoas privadas de liberdade no Brasil diante da pandemia do
    COVID-19". Disponível em:
    https://www.oas.org/pt/cidh/prensa/notas/2020/195.asp. Acesso em: 01
    abr. 2022.

[^7]: Ver: [Barreto Rodrigues _et al._ (2020), Campos; Alvarez (2017),
    Haber; Maciel (2018), Inacio; Bueno (2021]{.mark}), Jesus (2018;
    2020); [Lages; Ribeiro (2019), Maciel (2019), Ribeiro; Rocha (2017),
    Romano; Silva (2021), Semer (2019), Valois (2014, 2016), entre
    outros.]{.mark}

[^8]: Sobre a questão do saber policial ver [Muniz; Caruso; Freitas
    (2017)]{.mark} e Jesus (2020).

[^9]: Obras como as de Marcelo Semer (2019), Jesus (2018), Barreto
    Rodrigues; Pontes Fraga (2020), Casara (2015), Haber; Maciel (2018),
    Maciel (2019), Romano; Silva (2021), Valois (2014, 2016), dentre
    outras.

[^10]: Entendemos que a absolvição é um resultado diverso da
    desclassificação, sobretudo porque no primeiro caso a pessoa é
    inocentada da acusação e no segundo, apesar de inocentada do crime
    de tráfico de drogas, ainda responde por porte para uso, ou seja,
    ainda apresenta um processo contra si mesma. Contudo o objetivo do
    presente artigo é analisar casos em que os/as magistrados/as
    relativizam a narrativa policial sobre a ocorrência do crime de
    tráfico como central para a condenação de determinado acusado.

[^11]: Mobilizamos aqui neste artigo o termo "sistema de justiça
    criminal", adotado por parte da literatura sobre o direito, o qual
    se refere a todos os atores que atuam para o processamento criminal:
    promotores, defensores (públicos ou particulares) e magistrados.

[^12]: [Ver o trabalho de Cardoso (2020), em que o autor trabalha com a
    hipótese de que, num sistema de justiça em que a maioria de juízes é
    branca, entende-se a branquitude como o lugar da inocência em
    contraposição ao negro, compreendido como alguém potencialmente
    suspeito criminoso.]{.mark}

[^13]: Ambas as pesquisas acessaram os processos por meio do portal do
    Tribunal de Justiça: https://portal.tjsp.jus.br/.

[^14]: Certamente que esse recorte restringe o universo de casos para
    além daqueles que entraram no sistema em consequência de uma prisão
    em flagrante resultante de denúncia anônima. No entanto,
    compreendemos que esse enquadramento não compromete a análise que
    estamos propondo porque pretendemos olhar para os argumentos
    apresentados pelos magistrados para desclassificarem ou absolverem
    os envolvidos na denúncia de tráfico de drogas.

[^15]: Alguns casos exemplificam bem esse contexto, como o da juíza
    Kenarik Boujikian, analisado pela pesquisa Rafael Custódia em sua
    dissertação de mestrado (2021), e o caso do juiz Roberto Corcioli,
    apresentado na pesquisa da Conectas Direitos Humanos (2018).

[^16]: [Algumas pesquisas apontam para um campo de disputas com relação
    ao papel dos juízes no Brasil, sobretudo no período de reforma do
    Poder Judiciário nos anos 2000 e na Constituição Federal de 1998,
    que ampliou as formas individuais e coletivas de acesso ao
    Judiciário, como guardião dos direitos constitucionais do cidadão
    (Sadek, 2010; Bonelli, 2001; 2005; Gisiet *et al.*, 2019). No campo
    da justiça criminal, a literatura identifica entre os juízes um
    perfil chamado "garantista" ou "punitivista" (Carvalho, 2008; Bento,
    2013; Custódio, 2021; Valois, 2014; Semer, 2019).]{.mark}

[^17]: Essa classificação está amparada pelos trabalhos de Ferrajoli
    (2002) e Zaffaroni (2007), grandes referências no debate do
    garantismo, sobretudo no campo penal.

[^18]: A pena de censura representa uma das punições aplicadas aos
    magistrados segundo o Código de Ética da Magistratura. Além da pena
    de censura, há também as penas disciplinares de advertência, remoção
    compulsória, disponibilidade, aposentadoria compulsória e demissão.

[^19]: O termo é utilizado no site construído pelas diversas
    organizações mobilizadas pela aprovação da ação. Disponível em:
    https://www.adpfdasfavelas.org/. Acesso em: 09 mai. 2022.

[^20]: Ilustrativa dessa narrativa é a nota da Polícia Civil do Rio de
    Janeiro sobre a operação no bairro do Jacarezinho realizada em maio
    de 2021, que resultou em 28 mortes. Além de não mencionar tal fato,
    a nota justifica a operação em razão de notícias de que "traficantes
    vêm aliciando crianças e adolescentes para integrar a facção" e fala
    sobre as "táticas de guerrilha realizadas pelos marginais". Polícia
    Civil do Rio de Janeiro. *Polícia Civil realiza operação contra
    traficantes no Jacarezinho*. 06 mai. 2021. Disponível em:
    http://www.policiacivilrj.net.br/noticias.php?id=10632. Acesso em:
    09 mai. 2022.

[^21]: A decisão no RHC n. 158.580/BA pode ser lida na íntegra em:
    https://www.stj.jus.br/sites/portalp/SiteAssets/documentos/noticias/RHC%20158580%20Ministro%20Rogerio%20Schietti%20Cruz.pdf.
    Acesso em: 09 mai. 2022.
